# Header
blog_title: Red Line
subtitle: Blog Theme

menu:
  home: /
rss: /atom.xml

# Content
excerpt_link: Continue reading...
fancybox: true

# Miscellaneous
google_analytics: UA-XXXXXXXX
favicon: img/favicon.png
twitter: your-twitter
facebook: your-facebook
linkedin: your-linkedin
github: your-github
